### ISSUE TITLE
About result visualization

### ISSUE THREAD

**Issue by RoboticsZhang** [Asixa/RF-Genesis#1]
Hello! Thank you for your solid work and the code open-sourcing. I wonder that can you release some visualization scripts for each module (Object Diffusion, Environment Diffusion, and Path Diffusion) so that we can better understand each of them? Now the results are in .npy or .npz format, and they seem not easy to be visualized.

In addition, can you release some post-processing scripts for the final raw radar ADC bins that transform them to radar-azimuth heatmap or point clouds? 
This is the radar-azimuth heatmap result in GIF format using my radar post-processing code with the default prompt in this repo (there are a total of 65 frames, because the generated bin file has a shape of (65, 3, 4, 128, 256)), and I have changed the radar parameters according to /models/TI1843_config.json. 
![RF_Genesis_RAheatmap](https://github.com/Asixa/RF-Genesis/assets/61099841/69c150c5-26a6-4e14-9d13-a78b44d5942f)

The above result looks weird because there may be some flaws in my implementation. Hope that you can release your implementation when you are free! Thank you!

**Comment by Asixa** [comment]
Hi! 
Thank you for the suggestions. The basic visualization and point cloud processing code has been updated.
![ezgif-7-eec8a9c9af](https://github.com/Asixa/RF-Genesis/assets/22312333/a53ef6d7-18b3-4f02-a82a-5bca3aaf08f8)

Regards.
Xingyu.

**Comment by RoboticsZhang** [comment]
Hi Xingyu! 
Thank you again for the fast code update! I will close this issue then.

Best, 
Ruibin
