### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by wang-7** [Asixa/RF-Genesis#3]
Hello! I encountered this error when running the example. 
![image](https://github.com/Asixa/RF-Genesis/assets/73825059/e5275330-afdb-424c-98d2-30c9a71a1813)
![image](https://github.com/Asixa/RF-Genesis/assets/73825059/eaba115a-5afe-46db-bc9f-00e5cbf9444c)

**Comment by Asixa** [comment]
Hi,
Please comment out lines 59 to 62 in run.py and then continue. It seems that the issue is related to environment diffusion, which is not needed at the moment.

![image](https://github.com/Asixa/RF-Genesis/assets/22312333/d87f994c-1022-488a-8a20-2f7b5bb99b25)
